services:
  db:
    image: postgres:17
    container_name: raec-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5001:5432"
    volumes:
      - ./Dbase/init-complete.sql:/docker-entrypoint-initdb.d/init-complete.sql:ro
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  backend:
    build:
      context: ./Backend
    container_name: raec-backend
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${PASSWORD}@db:5432/${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}
      - FORM_DIR=${FORM_DIR}
      - REQ_DIR=${REQ_DIR}
      - PERIODO_DIR=${PERIODO_DIR}
      - FOLDER_DIR=${FOLDER_DIR}
    ports:
      - "4001:4001"
    volumes:
      - ./Backend/exports:/app/exports
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    build:
      context: ./Frontend/RAEC
    container_name: raec-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
      - db
    restart: unless-stopped

volumes:
  postgres_data:
